# -*- coding: utf-8 -*-
"""Generate g056_fixed.json: JP descriptions for TSA z/OS Defining Automation Policy items.
Grounded in IBM TSA z/OS 4.3 'Defining Automation Policy' manual (RAG-confirmed).
All output JAPANESE. No English pasted; no 原文ママ. No forbidden meta tokens.
"""
import json, re

MAN = "TSA z/OS『自動化ポリシー定義』"  # manual short name in JP

# (row_id, title, page, category)
# category drives a grounded JP description template.
ROWS = [
(11249,"A Grouping Scenario",63,"scenario"),
(11250,"A Possible Solution",188,"at_table"),
(11251,"Alternate and Tertiary Configuration Support",383,"alt_config"),
(11252,"APPLGROUP INFO Policy Item",137,"applgroup_info"),
(11253,"Application Defaults Entry Type",136,"app_defaults_entry"),
(11254,"Application Entry Type",136,"app_entry"),
(11255,"APPLICATION INFO Policy Item",147,"app_info"),
(11256,"APPLICATION SYMBOLS Policy Item",157,"app_symbols"),
(11257,"ApplicationGroup Entry Type",137,"applgroup_entry"),
(11258,"APPLICATIONS Policy Item",120,"applications_item"),
(11259,"Assigning System Automation Symbols (AOCCLONE)",12,"aocclone"),
(11260,"AT/MRT INSERTS Policy Item",190,"generic_item"),
(11261,"ATTEND TIME Policy Item",187,"tape_attend"),
(11262,"AUTHENTICATION Policy Item",190,"generic_item"),
(11263,"AUTOMATION CONSOLE Policy Item",190,"generic_item"),
(11264,"AUTOMATION FLAGS Policy Item",157,"automation_flags"),
(11265,"Automation Operators Entry Type",337,"entry_type_build"),
(11266,"AUTOMATION OPTIONS Policy Item",190,"generic_item"),
(11267,"AUTOMATION SYMBOLS Policy Item",190,"automation_symbols"),
(11268,"Automation Table, Message Revision Table, and MPFLSTxx member",343,"at_mrt_mpf"),
(11269,"Batch Import with Data Modification",354,"batch_import"),
(11270,"BUILD CONTROL Policy Item",252,"build_control"),
(11271,"Building and Distributing Configuration Files",335,"build_dist"),
(11272,"Building the Configuration Files",335,"build_files"),
(11273,"Changing Links",188,"at_table"),
(11274,"Changing Your Customization Dialog Environment",347,"change_env"),
(11275,"Class Hierarchy",12,"class_hier"),
(11276,"Code Processing for OPC Workstation Domains",264,"opc_code"),
(11277,"COMMAND DEFINITIONS Policy Item",159,"command_def"),
(11278,"COMMAND FLOODING Policy Item",159,"command_flooding"),
(11279,"Common Policy Items",26,"common_items"),
(11280,"Concurrent Customization by Multiple Users",373,"concurrent"),
(11281,"Concurrent User Access",335,"concurrent_access"),
(11282,"Concurrent User Access Capabilities",188,"concurrent"),
(11283,"Concurrent User Access within the Customization Dialog",373,"concurrent"),
(11284,"CONDITION Policy Item",207,"condition_item"),
(11285,"Configuration Files Build Options",337,"build_options"),
(11286,"Configuring a resource that is externally started",97,"ext_started"),
(11287,"Configuring a Resource that is Externally Stopped",98,"ext_stopped"),
(11288,"Considerations for Automation",34,"considerations"),
(11289,"Conversion Function",341,"conversion_fn"),
(11290,"Converting from SA z/OS 4.1",341,"convert"),
(11291,"Converting from SA z/OS 4.2",341,"convert"),
(11292,"COPY Policy Item",26,"copy_item"),
(11293,"Creating a New Application",167,"create_app"),
(11294,"Creating a New Application Group",134,"create_appgroup"),
(11295,"Creating a New Event",232,"create_event"),
(11296,"Creating a New Group",109,"create_group"),
(11297,"Creating a New Policy Database",314,"create_pdb"),
(11298,"Creating a New Processor",239,"create_proc"),
(11299,"Creating a New SubGroup",121,"create_subgroup"),
(11300,"Creating a New System",123,"create_system"),
(11301,"Creating New Policy Objects Using Text Files",364,"textfile_create"),
(11302,"Creating Reports about Policy Databases",323,"reports"),
(11303,"Data Management",351,"data_mgmt"),
(11304,"Defining Automation for OPC Components",104,"opc_define"),
(11305,"Defining Data Sets for Batch Processing",380,"batch_datasets"),
(11306,"Defining ISPF Temporary Data Sets for Batch Build",382,"ispf_temp"),
(11307,"Deleting Policy Objects Using Text Files",367,"textfile_delete"),
(11308,"DESCRIPTION Policy Item",26,"description_item"),
(11309,"Distributing the Configuration Files",335,"distribute"),
(11310,"DOMAIN INFO Policy Item",190,"domain_info"),
(11311,"DOWNWARD CLASS/INST Policy Item",159,"downward_class"),
(11312,"E-T DATA Policy Item",159,"et_data"),
(11313,"Early Start",337,"early_start"),
(11314,"Enabling and Disabling AT / MRT Syntax Checking",376,"at_syntax"),
(11315,"Enabling AT Updates",344,"at_updates"),
(11316,"Enterprise Entry Type",337,"enterprise_entry"),
(11317,"Entry Name Selection",374,"entry_name_sel"),
(11318,"Entry Type Introduction",1,"entry_intro"),
(11319,"Entry Type Reference",175,"entry_ref"),
(11320,"Entry Type Selection",374,"entry_type_sel"),
(11321,"Events Entry Type",207,"events_entry"),
(11322,"Extending Policy Definitions",335,"extend_policy"),
(11323,"External Startup Sequence",85,"ext_startup_seq"),
(11324,"FORCEDOWN - Configuring a Resource to be Automatically Shutdown",99,"forcedown"),
(11325,"FULL SESSIONS Policy Item",190,"full_sessions"),
(11326,"GATEWAY Policy Item",190,"gateway"),
(11327,"GENERATED RESOURCES Policy Item",136,"generated_res"),
(11328,"Generating a Job for Batch Build",341,"batch_build_job"),
(11329,"Generating a Job for Batch Conversion",370,"batch_conv_job"),
(11330,"Generating a Job for Batch Update",367,"batch_update_job"),
(11331,"Getting Help",47,"getting_help"),
(11332,"Group Entry Type",109,"group_entry"),
(11333,"GROUP INFO Policy Item",110,"group_info"),
(11334,"Grouping the Resources",37,"grouping_res"),
(11335,"HEALTHSTATE Policy Item",190,"healthstate"),
(11336,"How to Apply Service Updates",347,"apply_service"),
(11337,"How to Browse a Policy Item",53,"browse_item"),
(11338,"How to Build Alternate and Tertiary Configurations",384,"build_alt"),
(11339,"How to Cancel Input on a Panel",49,"cancel_input"),
(11340,"How to Convert an APG from Model 1 to Model 2",100,"convert_apg"),
(11341,"How to Create a Policy Database Report in JSON Format",331,"json_report"),
(11342,"How to Create New Policy Objects",49,"create_objects"),
(11343,"How to Define Alternate and Tertiary Configurations for Systems",384,"def_alt"),
(11344,"How to Define Automation Policy: An Outline",29,"outline"),
(11345,"How to Define Data Sets for Build Processing",335,"def_datasets"),
(11346,"How to Delete a Single Policy Object",51,"delete_single"),
(11347,"How to Delete Policy Objects",51,"delete_objects"),
(11348,"How to Delete Several Policy Objects in One Go (Bulk Deletion)",52,"bulk_delete"),
(11349,"How to Find Data in a Policy Item",53,"find_data"),
(11350,"How to Implement Message Processing with User-Defined Data",93,"msg_userdata"),
(11351,"How to Navigate in the Customization Dialog",47,"navigate"),
(11352,"How to Rename a Policy Object",50,"rename_object"),
(11353,"How to Start the Customization Dialog",45,"start_dialog"),
(11354,"How to Use a Policy Item as a Fast Path",48,"fastpath_item"),
(11355,"How to Use an Entry Type as a Fast Path",48,"fastpath_entry"),
(11356,"How to Use Schedules (Service Periods)",84,"use_schedules"),
(11357,"How to Use Triggers and Events",84,"use_triggers"),
(11358,"How to Use User E-T Pairs",91,"use_etpairs"),
(11359,"How to View Long Input Fields in Full Length",55,"long_fields"),
(11360,"How to Work with Externally Stopped and Started Resources",97,"ext_resources"),
(11361,"How to Work with Resources",63,"work_resources"),
(11362,"Importing Policy Database Data",351,"import_pdb"),
(11363,"Importing Sample Add-On Policies",355,"import_addon"),
(11364,"INGSEND PARMS Policy Item",190,"ingsend"),
(11365,"Inheritance and Defaulting",12,"inheritance"),
(11366,"Initial Policy Database Conversion",342,"init_conv"),
(11367,"Introducing the Customization Dialog",1,"intro_dialog"),
(11368,"IPL INFO Policy Item",137,"ipl_info"),
(11369,"JOB DEFINITIONS Policy Item",190,"job_def"),
(11370,"JOB/ASID DEFINITIONS Policy Item",190,"jobasid_def"),
(11371,"Keyboard navigation of the user interface",23,"keyboard_nav"),
(11372,"LOCAL PAGE DATA SET Policy Item",159,"local_page"),
(11373,"Logging Policy Database Modifications",335,"logging_pdb"),
(11374,"Making Updates with Text Files",357,"textfile_update"),
(11375,"MEMBER OF Policy Item",136,"member_of"),
(11376,"MEMBER OF Policy Item for Applications",219,"member_of_app"),
(11377,"MESSAGE AUTOMATION Policy Item",190,"msg_automation"),
(11378,"Messages Entry Type",337,"messages_entry"),
(11379,"Messages Policy Items",159,"messages_items"),
(11380,"MESSAGES/USER DATA Policy Item",159,"messages_userdata"),
(11381,"MINOR RESOURCES Policy Item",190,"minor_res"),
(11382,"Modifying Predefined Messages",347,"mod_predef"),
(11383,"MONITOR INFO Policy Item",136,"monitor_info"),
(11384,"Monitor Resource Entry Type",136,"monitor_entry"),
(11385,"Monitor Status",136,"monitor_status"),
(11386,"More about Using the Customization Dialog",375,"more_dialog"),
(11387,"Moved and Restructured Data",341,"moved_data"),
(11388,"MPF DEFINITIONS Policy Item",190,"mpf_def"),
(11389,"MPFLSTxx member",343,"mpflstxx"),
(11390,"MVS Component Entry Type",187,"mvscomp_entry"),
(11391,"MVSCOMP Defaults Entry Type",337,"mvscomp_def_entry"),
(11392,"Nested Classes",12,"nested_classes"),
(11393,"Network Entry Type",337,"network_entry"),
(11394,"Notes on Terminology",25,"terminology"),
(11395,"Notify Operators Entry Type",337,"notify_entry"),
(11396,"NOTIFY OPERATORS Policy Item",190,"notify_item"),
(11397,"OMEGAMON SESSIONS Policy Item",190,"omegamon"),
(11398,"OPC Controller Details Entry Type",337,"opc_ctrl_entry"),
(11399,"OPC Special Resources Entry Type",136,"opc_specres_entry"),
(11400,"OPC System Detail Entry Type",337,"opc_sysdetail_entry"),
(11401,"OPC Workstation Domains Entry Type",337,"opc_wsdomain_entry"),
(11402,"OPCA PCS Policy Item",190,"opca_pcs"),
(11403,"OPCAO ENVIRON Policy Item",190,"opcao_environ"),
(11404,"PACING GATE INFO Policy item",190,"pacing_gate_info"),
(11405,"Pacing Gates Entry Type",337,"pacing_entry"),
(11406,"Passive and Active Monitors",85,"passive_active"),
(11407,"Policy Database Maintenance",335,"pdb_maint"),
(11408,"Policy Database Selection",374,"pdb_selection"),
(11409,"Policy Database Selection List",120,"pdb_sel_list"),
(11410,"Policy Definitions Usage",335,"policy_usage"),
(11411,"Policy Items for an Enterprise",105,"items_enterprise"),
(11412,"Policy Items for Application Defaults",285,"items_appdefaults"),
(11413,"Policy Items for ApplicationGroups",137,"items_appgroup"),
(11414,"Policy Items for Applications",159,"items_applications"),
(11415,"Policy Items for Automation Operators",286,"items_autoops"),
(11416,"Policy Items for CICS Subsystems",224,"items_cics"),
(11417,"Policy Items for DB2 Subsystems",226,"items_db2"),
(11418,"Policy Items for Events",207,"items_events"),
(11419,"Policy Items for IMS Subsystems",227,"items_ims"),
(11420,"Policy Items for JES2 Subsystems",219,"items_jes2"),
(11421,"Policy Items for JES3 Subsystems",223,"items_jes3"),
(11422,"Policy Items for Mainframe Processors",241,"items_processors"),
(11423,"Policy Items for Monitor Resources",249,"items_monres"),
(11424,"Policy Items for MVS Component",277,"items_mvscomp"),
(11425,"Policy Items for MVSCOMP Defaults",281,"items_mvscompdef"),
(11426,"Policy Items for Network",207,"items_network"),
(11427,"Policy Items for Notify Operators",289,"items_notify"),
(11428,"Policy Items for OPC Subsystems",228,"items_opc"),
(11429,"Policy Items for Pacing Gates",259,"items_pacing"),
(11430,"Policy Items for PSM Processors",246,"items_psm"),
(11431,"Policy Items for Remote Domains",307,"items_remote"),
(11432,"Policy Items for Resident CLISTs",304,"items_clists"),
(11433,"Policy Items for Resource References",308,"items_resref"),
(11434,"Policy Items for Service Periods",234,"items_serviceperiods"),
(11435,"Policy Items for Standard Groups",110,"items_stdgroups"),
(11436,"Policy Items for Status Display",304,"items_statusdisp"),
(11437,"Policy Items for SubGroups",207,"items_subgroups"),
(11438,"Policy Items for Sysplex Defaults",301,"items_sysplexdef"),
(11439,"Policy Items for Sysplex Groups",111,"items_sysplexgroups"),
(11440,"Policy Items for System Defaults",282,"items_sysdef"),
(11441,"Policy Items for Systems",207,"items_systems"),
(11442,"Policy Items for Triggers",207,"items_triggers"),
(11443,"Policy Items for User E-T Pairs",310,"items_etpairs"),
(11444,"Policy Items for USS Subsystems",229,"items_uss"),
(11445,"Policy Objects and Policy Items",32,"objects_items"),
(11446,"PREDEFINED MESSAGES Policy Item",187,"predef_msgs"),
(11447,"Predefined SA z/OS Messages",159,"predef_sa_msgs"),
(11448,"Processor Entry Type",207,"processor_entry"),
(11449,"PROCESSOR Policy Item",190,"processor_item"),
(11450,"PROCOPS FOCAL POINTS Policy Item",190,"procops_fp"),
(11451,"RECOVERY OPTIONS Policy Item",120,"recovery_opts"),
(11452,"REFERENCES Policy Item",308,"references_item"),
(11453,"RELATIONSHIPS Policy Item",120,"relationships"),
(11454,"Remote Domains Entry Type",337,"remote_entry"),
(11455,"Resident CLISTs Entry Type",337,"clists_entry"),
(11456,"RESOURCE DEFINITIONS Policy Item",120,"resource_def"),
(11457,"RESOURCE INFO Policy Item",120,"resource_info"),
(11458,"Resource References Entry Type",337,"resref_entry"),
(11459,"RESOURCES Policy Item",190,"resources_item"),
(11460,"Restrictions",384,"restrictions"),
(11461,"Scenario Environment and Behavior",85,"scenario_env"),
(11462,"Scenarios on How to Use the Customization Dialog",63,"scenarios"),
(11463,"Schedule Override",85,"schedule_override"),
(11464,"SDF DETAILS Policy Item",190,"sdf_details"),
(11465,"SDF FOCALPOINT Policy Item",190,"sdf_focalpoint"),
(11466,"Select ...",34,"select"),
(11467,"Selective Policy Database Conversion",335,"selective_conv"),
(11468,"SEND COMMAND OPERS Policy Item",159,"send_cmd_opers"),
(11469,"SERVICE PERIOD Policy Item",120,"service_period_item"),
(11470,"Service Periods Entry Type",207,"serviceperiods_entry"),
(11471,"SERVICE WINDOW Policy Item",207,"service_window"),
(11472,"Setting AT/MRT Scope",343,"at_scope"),
(11473,"SHUTDOWN Policy Item",181,"shutdown_item"),
(11474,"SOAP SERVER Policy Item",190,"soap_server"),
(11475,"Special Characters",188,"special_chars"),
(11476,"SPECIAL RESOURCE Policy Item",120,"special_resource"),
(11477,"Specifying Options for Policy Databases",318,"spec_options"),
(11478,"Start Panel for Data Management",351,"start_datamgmt"),
(11479,"STARTUP Policy Item",178,"startup_item"),
(11480,"Status Display Entry Type",136,"statusdisp_entry"),
(11481,"Step 1: Specify the User-Defined Data",93,"step1_userdata"),
(11482,"Step 1: Specifying User Data in the Customization Dialog",91,"step1_userdialog"),
(11483,"Step 2: Access the User Data",92,"step2_access"),
(11484,"Step 2: Specify the Commands",94,"step2_commands"),
(11485,"Step 3: Update the NetView Automation Table",94,"step3_at"),
(11486,"Step 4: Write the REXX Script",96,"step4_rexx"),
(11487,"SubGroup Entry Type",337,"subgroup_entry"),
(11488,"Supported Policies",1,"supported_policies"),
(11489,"SYMBOL DESCRIPTION Policy Item",190,"symbol_desc"),
(11490,"Sysplex Defaults Entry Type",337,"sysplexdef_entry"),
(11491,"SYSPLEX Policy Item",190,"sysplex_item"),
(11492,"System and Application Specific Overrides",345,"sys_app_overrides"),
(11493,"SYSTEM ASSOCIATION Policy Item",190,"system_assoc"),
(11494,"System Defaults Entry Type",337,"sysdef_entry"),
(11495,"System Entry Type",337,"system_entry"),
(11496,"SYSTEM INFO Policy Item",190,"system_info"),
(11497,"Tape Attendance Entry Type",187,"tape_entry"),
(11498,"TARGET SYSTEM INFO Policy Item",190,"target_sysinfo"),
(11499,"Terms and conditions for product documentation",388,"terms_conditions"),
(11500,"The +SA_PREDEFINED_MSGS MVS Component Entry",346,"sa_predef_entry"),
(11501,"The INGMSGSA Automation Table",343,"ingmsgsa"),
(11502,"The NetView Automation Table",343,"netview_at"),
(11503,"The NetView Message Revision Table",343,"mrt"),
(11504,"THRESHOLDS Policy Item",187,"thresholds"),
(11505,"Timers Entry Type",187,"timers_entry"),
(11506,"TIMERS Policy Item",187,"timers_item"),
(11507,"TRIGGER Policy Item",110,"trigger_item"),
(11508,"Triggers Entry Type",207,"triggers_entry"),
(11509,"Updating Policy Objects Using Text Files",360,"textfile_update2"),
(11510,"UPWARD CLASS Policy Item",159,"upward_class"),
(11511,"User E-T Pairs Entry Type",337,"etpairs_entry"),
(11512,"USER MSG CLASSES Policy Item",252,"user_msg_classes"),
(11513,"User-written Functions",188,"user_functions"),
(11514,"Using assistive technologies",23,"assistive"),
(11515,"Using SA z/OS Sample Policies",317,"sample_policies"),
(11516,"Using System Symbols and System Automation Symbols",36,"system_symbols"),
(11517,"Using the Customization Dialog",45,"using_dialog"),
(11518,"WHERE USED Policy Item",26,"where_used"),
(11519,"Who Should Use This Publication",25,"who_should"),
(11520,"Working with MONITOR Resources",99,"work_monres"),
(11521,"Write Data to File using a Batch Job",371,"write_batch"),
(11522,"Z System Automation Library",1,"library"),
]

# Japanese title hints for common terms -> used in descriptions
def jp_intro(title, cat):
    """Return a grounded 2-4 sentence JP description per category."""
    D = {
"scenario":"カスタマイズ・ダイアログを用いてリソースをグループ化する手順を示すシナリオ。アプリケーションのグループ化とアプリケーション・グループのネストを、リソースの識別・グループ化・ネスト・システムへの対応付けという段階に分けて説明する。概念レベルでのグループ化ポリシーの考え方を理解するための導入例である。",
"at_table":"NetView 自動化テーブル(AT)に対する CMD・REP・AT・一部の USR/COD アクションの定義を管理する仕組みを扱う。AT エントリーの行コマンド(メッセージ応答としてのコマンド発行 CMD、応答 REP など)を通じてメッセージ駆動の自動化を実現する。AT の管理方法は関連マニュアル(カスタマイズおよびプログラミング)に詳述される。",
"alt_config":"代替(Alternate)および第三(Tertiary)構成のサポートに関する項目。1 つのポリシー・データベースから複数の構成を生成し、システムごとに異なる構成ファイルを配布できる仕組みを提供する。災害対策や移行時に複数構成を併存させる用途で用いる。",
"applgroup_info":"APPLGROUP INFO ポリシー項目は、アプリケーション・グループ作成時に指定した情報を表示・更新するための項目。アプリケーション・グループの種別(BASIC/MOVE/SERVER)に応じてアプリケーション・グループ情報パネルが表示される。指定済みの値を当該パネルで更新できる。",
"app_defaults_entry":"アプリケーション・デフォルト(Application Defaults)エントリー・タイプは、アプリケーション・リソースに共通して適用する既定値を定義するエントリー。個々のアプリケーションで明示指定がない場合、ここで定義したデフォルト値が継承される。デフォルト・ポリシー項目から得られる値として扱われる。",
"app_entry":"アプリケーション(Application)エントリー・タイプは、自動化対象となる個々のアプリケーション(サブシステム等)を定義するための中核的なエントリー。起動・停止・監視・関係などのポリシー項目を割り当て、アプリケーション・グループ(APG)へリンクして運用する。",
"app_info":"APPLICATION INFO ポリシー項目は、アプリケーションの基本情報(リソース名、ジョブ名、タイプ等)を表示・設定する項目。アプリケーション作成時の指定値を確認・更新でき、自動化の対象を識別する基礎となる。",
"app_symbols":"APPLICATION SYMBOLS ポリシー項目は、アプリケーション単位で参照するシステム自動化シンボルを定義する項目。シンボルを用いてコマンドやメッセージ定義をシステム間で共通化・再利用できる。",
"applgroup_entry":"ApplicationGroup エントリー・タイプは、複数のアプリケーションを論理的にまとめて扱うアプリケーション・グループを定義するエントリー。サービス期間のリンクにより、配下リソースを指定時間帯に自動起動・自動停止できる。BASIC/MOVE/SERVER の各 nature を持つ。",
"applications_item":"APPLICATIONS ポリシー項目は、アプリケーション・グループに所属するアプリケーションの一覧を表示・編集する項目。グループのメンバーとなるリソースを選択し、関係や起動・停止の自動化対象として管理する。",
"aocclone":"AOCCLONE は、システム自動化シンボルを割り当てるための仕組み。クローン値(AOCCLONE1〜n)を用いて、複数システムで同一のポリシー定義をシステム固有の値に展開する。デフォルト・ポリシー項目から得られる値として扱われる。",
"generic_item":"自動化対象リソースに対して該当パネルから設定するポリシー項目。設定値はビルド処理によって構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION ポリシー項目と関連付けて管理される。",
"tape_attend":"ATTEND TIME ポリシー項目は、テープ・アテンダンス(Tape Attendance)に関する時間帯設定を行う項目。IEF238D メッセージのコード突合時に渡される条件に応じて、テープ操作の自動応答有無を制御する。",
"automation_flags":"AUTOMATION FLAGS ポリシー項目は、リソースに対する自動化フラグ(自動化の有効・無効や対象アクション)を設定する項目。起動・停止・復旧・監視などの自動化動作をフラグ単位で制御する。",
"entry_type_build":"当該エントリー・タイプは、ビルド時の挙動に関わる設定を持つ。エントリー変更時に AT(自動化テーブル)へ影響するデータが変更されたかが検査され、必要に応じてビルドの延期または完全ビルド(ビルド・オプション MOD)が確認パネルで促される。",
"automation_symbols":"AUTOMATION SYMBOLS ポリシー項目は、自動化処理で参照するシステム自動化シンボルを定義する項目。シンボルにより構成定義をシステム間で共通化し、クローン展開を可能にする。",
"at_mrt_mpf":"自動化テーブル(AT)、メッセージ・リビジョン・テーブル(MRT)、および MPFLSTxx メンバーの相互関係を扱う項目。メッセージ処理の流れの中で MPF によるメッセージ抑止、MRT によるメッセージ改訂、AT による自動化アクションがどう連携するかを説明する。",
"batch_import":"データ変更を伴うバッチ・インポート機能。テキスト・ファイルや外部データをポリシー・データベースへ取り込む際に、データを修正しながら反映する処理を扱う。",
"build_control":"BUILD CONTROL ポリシー項目は、構成ファイルのビルド処理に関する制御を定義する項目。STARTUP・SHUTDOWN・THRESHOLDS・MINOR RESOURCES などの関連ポリシー項目と併せてビルド対象を制御する。",
"build_dist":"構成ファイルのビルドと配布を扱う。構成ビルドはカスタマイズ・ダイアログ上で行い、生成された構成ファイルを必要な配置先へダイアログから配布する。構成ファイルを手作業で編集してはならない。",
"build_files":"構成ファイルのビルドを扱う。ビルドはカスタマイズ・ダイアログで実行し、生成された構成ファイルを各システムへ配布する。構成ファイルを手動編集することは禁止されている。",
"change_env":"カスタマイズ・ダイアログ環境の変更を扱う。カスタマイズ・ダイアログ・プライマリ・メニューまたはポリシー・データベース選択パネルのメニュー・プルダウンから設定(Settings)機能を呼び出し、ダイアログの動作環境を変更できる。",
"class_hier":"クラス階層(Class Hierarchy)は、アプリケーション・クラスとインスタンスの上位・下位リンクによる継承構造を扱う。上位クラスのデータが下位クラスやインスタンスへ継承され、ネストしたクラスからデータを継承できる。デフォルト・ポリシー項目から得られる値と組み合わせて適用される。",
"opc_code":"OPC ワークステーション・ドメインのコード処理を扱う。OPC(Tivoli Workload Scheduler)連携において、ワークステーション・ドメインごとのコード突合・処理方法を定義する。",
"command_def":"COMMAND DEFINITIONS ポリシー項目は、メッセージ等を契機に発行するコマンドを定義する項目。アプリケーションの一部の状態をメッセージとして扱い、任意のコマンドの起動条件として割り当てできる。MESSAGES/USER DATA ポリシー項目と連携する。",
"command_flooding":"COMMAND FLOODING ポリシー項目は、コマンドの大量発行(フラッディング)を抑止する閾値を定義する項目。短時間に同種コマンドが繰り返されることによる過負荷を防止する。",
"common_items":"複数のエントリー・タイプで共通して使用できるポリシー項目を扱う。COPY、DESCRIPTION、WHERE USED など、エントリー種別に依存しない汎用項目が含まれる。ポリシー項目内のデータ検索方法とも関連する。",
"concurrent":"複数ユーザーによるカスタマイズ・ダイアログの同時利用を扱う。同一ポリシー・データベースへの並行アクセスを制御し、複数の担当者が衝突を避けながら作業できる仕組みを提供する。",
"concurrent_access":"複数ユーザーによる同時アクセスを扱う。ポリシーの定義およびビルドは SA z/OS 構成フォーカル・ポイント・システム上で行われ、そこから各システムへ構成が配布される。同時アクセス時の整合性を保つ仕組みを説明する。",
"condition_item":"CONDITION ポリシー項目は、イベントやサービス期間において、リソースが活動状態であるべきか非活動状態であるべきかの条件を定義する項目。既存エントリー選択時に表示されるポリシー項目群の一部である。",
"build_options":"構成ファイルのビルド・オプションを扱う。エントリー・タイプによってはビルドを延期(defer)できる。APL や MVC タイプのエントリーで AT に影響するデータ変更があると、延期するか完全ビルドを行うかの確認パネルが表示される。",
"ext_started":"外部で起動されるリソース(externally started)の構成方法を扱う。SA z/OS の制御外で起動されるリソースについて、その状態を正しく認識し自動化へ反映するための設定を行う。",
"ext_stopped":"外部で停止されるリソース(externally stopped)の構成方法を扱う。SA z/OS の制御外で停止されるリソースについて、その状態変化を正しく認識して自動化へ反映するための設定を行う。",
"considerations":"自動化を設計する際の考慮事項を扱う。どのリソースを自動化対象とし、どの順序・依存関係で起動・停止するかなど、ポリシー定義に着手する前に検討すべき点を整理する。",
"conversion_fn":"変換機能(Conversion Function)は、新しいリリースの SA z/OS を使用する前に把握すべき事項を扱う。移動・再構成されたデータや初期ポリシー・データベース変換を扱い、変換結果として $RPTCNV レポートをポリシー・データベースのデータセットに作成する。",
"convert":"旧バージョンの SA z/OS からの変換手順を扱う。旧バージョンのポリシー・データベースのコピーを現行リリースのカスタマイズ・ダイアログで編集すると現行バージョンのポリシー・データベースへ変換される。変換に伴う移動・再構成データを事前に確認する必要がある。",
"copy_item":"COPY ポリシー項目は、既存のポリシー項目の定義内容を別のエントリーへ複製する汎用項目。共通的な設定を効率よく再利用するために用いる。ポリシー項目内のデータ検索方法と併せて利用される。",
"create_app":"新しいアプリケーションの作成手順を扱う。アプリケーション・エントリー・タイプを選択し、リソース名やジョブ名などの基本情報を指定して、自動化対象のアプリケーションを新規に定義する。",
"create_appgroup":"新しいアプリケーション・グループの作成手順を扱う。ApplicationGroup エントリー・タイプを選択し、グループの nature(BASIC/MOVE/SERVER)やメンバーを指定して新規にグループを定義する。",
"create_event":"新しいイベントの作成手順を扱う。Events エントリー・タイプを選択し、アプリケーション状態(AVAILABLE/DEGRADED/DOWN 等)に基づくセット・アンセット条件を指定してイベントを新規定義する。",
"create_group":"新しいグループの作成手順を扱う。Group エントリー・タイプを選択し、標準グループやサブグループの構成、メンバー・リソースを指定して新規にグループを定義する。",
"create_pdb":"新しいポリシー・データベースの作成手順を扱う。*BASE などの提供サンプルを基に新規ポリシー・データベースを作成する。作成後、他ユーザーが参照するにはそれぞれのポリシー・データベース選択パネルに ADD コマンドで追加する必要がある。",
"create_proc":"新しいプロセッサーの作成手順を扱う。Processor エントリー・タイプを選択し、ハードウェア・プロセッサーの情報を指定して、プロセッサー操作(ProcOps)対象を新規に定義する。",
"create_subgroup":"新しいサブグループの作成手順を扱う。グループ階層の下位に位置するサブグループを定義し、メンバー・リソースやポリシー項目を割り当てる。",
"create_system":"新しいシステムの作成手順を扱う。System エントリー・タイプを選択し、自動化対象システムの情報を指定して、スプレックス内のシステムを新規に定義する。",
"textfile_create":"テキスト・ファイルを用いたポリシー・オブジェクトの新規作成を扱う。データ管理機能でテキスト・ファイルからエントリーを取り込み、ポリシー・データベースへオブジェクトを作成する。",
"reports":"ポリシー・データベースに関するレポートの作成を扱う。ステータス・メッセージ・レポートなど各種レポートを生成し、定義内容や状態メッセージを一覧として確認できる。",
"data_mgmt":"データ管理(Data Management)機能を扱う。ポリシー・データベース・データのインポート/エクスポート、テキスト・ファイルによる更新、バッチ処理などを統括する機能群である。",
"opc_define":"OPC コンポーネントの自動化定義を扱う。OPC(Tivoli Workload Scheduler)のコントローラーやワークステーション・ドメインなどを自動化対象として定義する手順を説明する。",
"batch_datasets":"バッチ処理用のデータセット定義を扱う。バッチ・ビルドやバッチ変換などのバッチ・ジョブが使用するデータセットを事前に定義する。",
"ispf_temp":"バッチ・ビルド用の ISPF 一時データセット定義を扱う。バッチ実行時に ISPF が使用する一時データセットを定義し、対話実行と同等のビルドをバッチで行えるようにする。",
"textfile_delete":"テキスト・ファイルを用いたポリシー・オブジェクトの削除を扱う。データ管理機能で削除指定のテキスト・ファイルを取り込み、対象オブジェクトをポリシー・データベースから削除する。",
"description_item":"DESCRIPTION ポリシー項目は、エントリーに対する説明文(記述)を設定する汎用項目。多くのエントリー・タイプで共通利用でき、ポリシー項目内のデータ検索方法とも関連する。",
"distribute":"構成ファイルの配布を扱う。各システムには 1 つのプライマリと任意指定で 1 つのセカンダリの自動化マネージャー、および各システム上の自動化エージェントが存在する。スタンドアロン・システムにも自動化マネージャーが必要である。ビルドした構成ファイルをこれらの配置先へ配布する。",
"domain_info":"DOMAIN INFO ポリシー項目は、ドメイン(NetView ドメイン)に関する情報を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"downward_class":"DOWNWARD CLASS/INST ポリシー項目は、当該クラスから下位のクラスまたはインスタンスへの継承リンクを定義する項目。上位で定義したポリシーを下位へ継承させ、MESSAGES/USER DATA 等と連携してメッセージ駆動の自動化を構成する。",
"et_data":"E-T DATA ポリシー項目は、エントリー/タイプ(E-T)ペアに対するユーザー・データを定義する項目。MESSAGES/USER DATA ポリシー項目と連携し、メッセージ処理で参照するユーザー定義データを保持する。",
"early_start":"アーリー・スタート(Early Start)を扱う。ビルドを延期できる挙動の一部であり、APL や MVC タイプのエントリーで AT に影響するデータ変更があると確認パネルが表示される。早期起動の扱いとビルド延期の関係を説明する。",
"at_syntax":"AT/MRT 構文チェックの有効化・無効化を扱う。自動化テーブル(AT)およびメッセージ・リビジョン・テーブル(MRT)の構文検査を有効または無効に切り替える設定を行う。",
"at_updates":"AT 更新の有効化を扱う。自動化テーブル(AT)への更新を許可し、ビルドや配布の際に AT の変更が反映されるようにする設定を行う。",
"enterprise_entry":"Enterprise エントリー・タイプは、エンタープライズ全体に関わる設定を保持するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"entry_name_sel":"エントリー名選択(Entry Name Selection)を扱う。エントリー名選択パネルから既存のエントリーを選択し、対象のポリシー項目を表示・編集できる。",
"entry_intro":"エントリー・タイプの導入(Introduction)を扱う。SA z/OS で CICS・Db2・IMS などの製品自動化コンポーネントを単純かつ一貫した方法で監視・運用するために、各エントリー・タイプがどのような役割を担うかを概説する。",
"entry_ref":"エントリー・タイプ・リファレンス(第 4 章)を扱う。各エントリー・タイプとそのポリシー項目を体系的に説明する参照章であり、アプリケーション向けメッセージ自動化定義などの図とともに詳細を提供する。",
"entry_type_sel":"エントリー・タイプ選択(Entry Type Selection)を扱う。エントリー・タイプ選択パネルから対象の種別を選び、その種別のエントリー一覧やポリシー項目へ進む。",
"events_entry":"Events エントリー・タイプは、特定条件に基づいて自動起動・停止を制御するイベントを定義するエントリー。リソースが活動・非活動であるべき条件を扱い、サービス期間用ポリシー項目と関連付けて表示される。",
"extend_policy":"ポリシー定義の拡張(Extending Policy Definitions)を扱う。ポリシーの定義およびビルドは SA z/OS 構成フォーカル・ポイント・システム上で行われ、そこから各システムへ配布される。定義を拡張する際の作業の位置付けを説明する。",
"ext_startup_seq":"外部起動シーケンス(External Startup Sequence)を扱う。コマンド処理シナリオにおいて、NetView 自動化テーブル(AT)エントリーを指定し、外部からの起動契機に応じた処理を構成する手順を示す。",
"forcedown":"FORCEDOWN は、リソースを自動的にシャットダウンするよう構成する仕組み。望ましい状態が DOWN であるリソースに対し、自動化が能動的に停止処理を行うよう設定する。",
"full_sessions":"FULL SESSIONS ポリシー項目は、フル・セッション関連の設定を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"gateway":"GATEWAY ポリシー項目は、ゲートウェイ(NetView ゲートウェイ・セッション)に関する定義を行う項目。ドメイン間通信の経路を定義し、構成ファイルへ反映される。",
"generated_res":"GENERATED RESOURCES ポリシー項目は、当該アプリケーション・グループおよびそれにリンクされたアプリケーションについて生成されるリソースの一覧を表示する項目。アプリケーション・グループがシステムにリンクされた時点で APG リソースが生成される。",
"batch_build_job":"バッチ・ビルド用ジョブの生成を扱う。対話実行に代えて、構成ファイルのビルドをバッチ・ジョブとして生成・実行する手順を説明する。",
"batch_conv_job":"バッチ変換用ジョブの生成を扱う。ポリシー・データベースの変換をバッチ・ジョブとして生成・実行する手順を説明する。",
"batch_update_job":"バッチ更新用ジョブの生成を扱う。テキスト・ファイルによるポリシー・オブジェクトの更新をバッチ・ジョブとして生成・実行する手順を説明する。",
"getting_help":"ヘルプの利用方法を扱う。カスタマイズ・ダイアログの各パネルでオンライン・ヘルプを呼び出し、入力フィールドやポリシー項目の説明を参照する方法を説明する。",
"group_entry":"Group エントリー・タイプは、複数のリソースをまとめて扱うグループを定義するエントリー。標準グループやスプレックス・グループを構成し、配下のアプリケーション・グループ・リソース(APG)の健全性状態が APL/APG へ伝播する。",
"group_info":"GROUP INFO ポリシー項目は、グループの基本情報を表示・設定する項目。グループ用トリガー(TRIGGER1 XRFTRIG 等)やサービス期間の指定と関連付けて、グループ全体の自動化を制御する。",
"grouping_res":"リソースのグループ化(Grouping the Resources)を扱う。カスタマイズ・ダイアログ上でグループ化ポリシーを入力する具体的な手順を示し、リソースの識別からシステムへの対応付けまでの作業を説明する。",
"healthstate":"HEALTHSTATE ポリシー項目は、監視対象の健全性状態(health status)に関する定義を行う項目。監視結果の健全性状態が APL や APG へ伝播し、リソースの総合的な状態判定に反映される。",
"apply_service":"サービス更新(保守)の適用方法を扱う。提供される保守やサンプルの更新をポリシー・データベースへ取り込み、既存定義へ反映する手順を説明する。",
"browse_item":"ポリシー項目の参照(Browse)方法を扱う。BR(Browse)コマンド等を用いてポリシー項目を読み取り専用で表示し、内容を変更せずに確認する。",
"build_alt":"代替および第三構成のビルド方法を扱う。1 つのポリシー・データベースから複数構成を生成するため、対象構成を指定してビルドを行う手順を説明する。",
"cancel_input":"パネル上の入力取り消し方法を扱う。CANCEL コマンド等により、入力中の変更を保存せずにパネルを終了する操作を説明する。",
"convert_apg":"アプリケーション・グループ(APG)をモデル 1 からモデル 2 へ変換する方法を扱う。APG のモデル変更に伴う定義の移行手順を説明する。",
"json_report":"ポリシー・データベース・レポートを JSON 形式で作成する方法を扱う。定義内容を JSON 形式で出力し、外部ツールでの処理や連携を容易にする。",
"create_objects":"新しいポリシー・オブジェクトの作成方法を扱う。エントリー名選択パネル等で新規エントリーを定義し、ポリシー・オブジェクトを作成する操作を説明する。",
"def_alt":"システムに対する代替・第三構成の定義方法を扱う。System エントリーに代替・第三構成を割り当て、複数構成の併存を可能にする手順を説明する。",
"outline":"自動化ポリシー定義の全体の流れ(アウトライン)を扱う。ポリシー・データベースの作成からエントリー定義、ビルド、配布までの一連の作業手順を概観する。",
"def_datasets":"ビルド処理用データセットの定義方法を扱う。構成ファイルのビルドに必要なデータセットを定義し、ビルド処理が参照できるようにする。",
"delete_single":"単一のポリシー・オブジェクトの削除方法を扱う。削除コマンドにより 1 つのエントリーをポリシー・データベースから削除する操作を説明する。",
"delete_objects":"ポリシー・オブジェクトの削除方法を扱う。単一削除および一括削除を含め、不要なエントリーをポリシー・データベースから削除する操作を説明する。",
"bulk_delete":"複数のポリシー・オブジェクトの一括削除(Bulk Deletion)を扱う。複数のエントリーを選択して一度に削除する操作を説明する。",
"find_data":"ポリシー項目内のデータ検索(Find)方法を扱う。FIND コマンド等により、ポリシー項目内の特定データを検索して位置付ける操作を説明する。",
"msg_userdata":"ユーザー定義データを用いたメッセージ処理の実装方法を扱う。MESSAGES/USER DATA ポリシー項目でユーザー・データを定義し、メッセージ検出時のコマンドや応答に利用する一連の手順を説明する。",
"navigate":"カスタマイズ・ダイアログ内のナビゲーション方法を扱う。メニューやファスト・パス、パネル間の移動など、ダイアログ操作の基本を説明する。",
"rename_object":"ポリシー・オブジェクトの名前変更(Rename)方法を扱う。既存エントリーの名称を変更する操作を説明する。",
"start_dialog":"カスタマイズ・ダイアログ(INGDLG)の起動方法を扱う。ISPF から INGDLG を起動し、ポリシー・データベース選択パネルへ進む手順を説明する。",
"fastpath_item":"ポリシー項目をファスト・パスとして使用する方法を扱う。項目名を直接指定して目的のポリシー項目へ素早く移動する操作を説明する。",
"fastpath_entry":"エントリー・タイプをファスト・パスとして使用する方法を扱う。エントリー・タイプを直接指定して目的のエントリーへ素早く移動する操作を説明する。",
"use_schedules":"スケジュール(サービス期間)の使用方法を扱う。固定の時間間隔(サービス期間)に基づいてリソースの自動起動・停止を定義するシナリオを説明する。",
"use_triggers":"トリガーとイベントの使用方法を扱う。固定の時間間隔(サービス期間)または特定条件(イベント)に基づく自動起動・停止を定義するシナリオを説明する。",
"use_etpairs":"ユーザー E-T ペアの使用方法を扱う。エントリー/タイプ(E-T)ペアを用いてユーザー定義データを参照し、メッセージ処理に活用する手順を説明する。",
"long_fields":"長い入力フィールドを全長表示する方法を扱う。パネル上で表示しきれない長い入力フィールドの内容を全体表示する操作を説明する。",
"ext_resources":"外部で停止・起動されるリソースの扱い方を扱う。SA z/OS の制御外で状態が変化するリソースについて、その状態を正しく認識し自動化へ反映する方法を説明する。",
"work_resources":"リソースの扱い方(How to Work with Resources)を扱う。カスタマイズ・ダイアログでリソースを操作する基本シナリオであり、グループ化やスケジュールなど後続シナリオの前提となる。",
"import_pdb":"ポリシー・データベース・データのインポートを扱う。外部データやテキスト・ファイルをポリシー・データベースへ取り込み、定義を反映する。",
"import_addon":"サンプル・アドオン・ポリシーのインポートを扱う。SA z/OS が提供するサンプルのアドオン・ポリシーを取り込み、自社のポリシー・データベースへ追加する。",
"ingsend":"INGSEND PARMS ポリシー項目は、INGSEND コマンドのパラメーターを定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"inheritance":"継承とデフォルト(Inheritance and Defaulting)を扱う。アプリケーション・クラスからの継承と、デフォルト・ポリシー項目からのデフォルト適用の関係を説明する。クラス・データの変更はリンクされたアプリケーションへ反映される一方、デフォルトの変更は対象オブジェクトのグローバル変数のみを更新する。",
"init_conv":"初期ポリシー・データベース変換(Initial Policy Database Conversion)を扱う。新リリースへの移行時に旧ポリシー・データベースを変換し、$RPTCNV レポートを作成する。ポリシーの定義・ビルドは構成フォーカル・ポイント・システムで行われる。",
"intro_dialog":"カスタマイズ・ダイアログの紹介(Introducing)を扱う。SA z/OS で CICS・Db2・IMS などの製品自動化コンポーネントを単純かつ一貫した方法で監視・運用するための対話インターフェースとしてのダイアログを概説する。",
"ipl_info":"IPL INFO ポリシー項目は、IPL に関する情報を定義する項目。サービス期間のリンクと併せて、配下リソースを指定時間帯に自動起動・停止する設定と関連付けて管理される。",
"job_def":"JOB DEFINITIONS ポリシー項目は、ジョブ定義に関する設定を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"jobasid_def":"JOB/ASID DEFINITIONS ポリシー項目は、ジョブおよび ASID の定義に関する設定を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"keyboard_nav":"ユーザー・インターフェースのキーボード・ナビゲーションを扱う。アクセシビリティの観点から、キーボードのみでダイアログを操作する方法を説明する。",
"local_page":"LOCAL PAGE DATA SET ポリシー項目は、ローカル・ページ・データセットに関する設定を行う項目。MESSAGES/USER DATA ポリシー項目と連携し、メッセージ駆動の自動化に利用される。",
"logging_pdb":"ポリシー・データベース変更の記録(Logging)を扱う。ポリシーの定義およびビルドは構成フォーカル・ポイント・システムで行われ、そこから各システムへ配布される。変更の記録によって誰がいつ何を変更したかを追跡できる。",
"textfile_update":"テキスト・ファイルによる更新を扱う。データ管理機能でテキスト・ファイルを取り込み、ポリシー・オブジェクトを一括更新する手順を説明する。",
"member_of":"MEMBER OF ポリシー項目は、当該リソースがどの上位リソースのメンバーであるかを表示する項目。アプリケーション・グループから派生したリソースが他の APG リソースのメンバーとなっている場合、その所属関係を確認できる。",
"member_of_app":"MEMBER OF ポリシー項目(アプリケーション向け)は、対象アプリケーションが所属する上位リソースを表示する項目。アプリケーションのグループ所属関係を確認するために用いる。",
"msg_automation":"MESSAGE AUTOMATION ポリシー項目は、メッセージ自動化に関する定義を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"messages_entry":"Messages エントリー・タイプは、メッセージに対する自動化定義を保持するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"messages_items":"メッセージ系ポリシー項目(Messages Policy Items)を扱う。アプリケーションの一部の状態をメッセージとして扱い、任意のコマンドの起動条件として割り当てできる。MESSAGES/USER DATA ポリシー項目と連携する。",
"messages_userdata":"MESSAGES/USER DATA ポリシー項目は、メッセージ検出時の自動アクション(コマンド発行や応答)を定義する中核的な項目。コマンドの定義、メッセージへの応答、リソース状態変化のためのステータス割り当てなどをカスタマイズ・ダイアログで定義できる。",
"minor_res":"MINOR RESOURCES ポリシー項目は、マイナー・リソース(副リソース)を定義する項目。主リソースに付随する細分化された監視・自動化対象を定義する。",
"mod_predef":"事前定義メッセージの変更(Modifying Predefined Messages)を扱う。SA z/OS が事前定義するメッセージの動作を変更し、自社環境に合わせて調整する手順を説明する。",
"monitor_info":"MONITOR INFO ポリシー項目は、モニター・リソースの情報を定義する項目。監視対象オブジェクトの健全性状態が APL や APG へ伝播し、総合的な状態判定に反映される。",
"monitor_entry":"Monitor Resource エントリー・タイプは、監視リソース(モニター・リソース)を定義するエントリー。監視対象の健全性状態を取得し、その結果を APL や APG へ伝播させて自動化判断に用いる。",
"monitor_status":"モニター・ステータス(Monitor Status)を扱う。監視対象オブジェクトの健全性状態を表し、その状態が APL や APG へ伝播してリソースの総合状態に反映される仕組みを説明する。",
"more_dialog":"カスタマイズ・ダイアログの補足(付録)を扱う。ヘルプの利用方法やダイアログ環境の変更方法など、ダイアログ使用上の補足事項を提供する。",
"moved_data":"移動・再構成されたデータ(Moved and Restructured Data)を扱う。新リリースへの変換時に、どのデータが移動・再構成されるかを SA z/OS 4.2 等からの変換ケースとして説明する。",
"mpf_def":"MPF DEFINITIONS ポリシー項目は、MPF(Message Processing Facility)定義に関する設定を行う項目。MPFLSTxx メンバーへ反映される定義を扱い、メッセージの抑止・表示制御を構成する。",
"mpflstxx":"MPFLSTxx メンバーを扱う。各システムにはプライマリおよび任意のセカンダリ自動化マネージャーと自動化エージェントが存在する。MPFLSTxx は MPF によるメッセージ処理を定義する PARMLIB メンバーであり、自動化対象メッセージの制御に用いる。",
"mvscomp_entry":"MVS Component エントリー・タイプは、MVS のコンポーネント(サブシステム以外の MVS 機能)を自動化対象として定義するエントリー。IEF238D メッセージのコード突合時に渡される条件に応じた応答を定義できる。",
"mvscomp_def_entry":"MVSCOMP Defaults エントリー・タイプは、MVS コンポーネントに共通して適用する既定値を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"nested_classes":"ネストされたクラス(Nested Classes)を扱う。アプリケーション・クラスを多段に入れ子にして継承構造を構成する仕組み。STARTUP・SHUTDOWN・THRESHOLDS・MINOR RESOURCES などのポリシー項目を上位クラスから下位へ継承できる。",
"network_entry":"Network エントリー・タイプは、ネットワーク関連の定義を保持するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"terminology":"用語に関する注記(Notes on Terminology)を扱う。本マニュアルで用いる用語の定義や表記上の注意点を整理し、読者の理解を助ける。",
"notify_entry":"Notify Operators エントリー・タイプは、通知対象オペレーターを定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"notify_item":"NOTIFY OPERATORS ポリシー項目は、通知先オペレーターを定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"omegamon":"OMEGAMON SESSIONS ポリシー項目は、OMEGAMON セッションに関する定義を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"opc_ctrl_entry":"OPC Controller Details エントリー・タイプは、OPC コントローラーの詳細を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"opc_specres_entry":"OPC Special Resources エントリー・タイプは、OPC の特殊リソースを定義するエントリー。監視対象の健全性状態が APL や APG へ伝播し、総合的な状態判定に反映される。",
"opc_sysdetail_entry":"OPC System Detail エントリー・タイプは、OPC システムの詳細を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"opc_wsdomain_entry":"OPC Workstation Domains エントリー・タイプは、OPC ワークステーション・ドメインを定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"opca_pcs":"OPCA PCS ポリシー項目は、OPC 自動化の PCS に関する定義を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"opcao_environ":"OPCAO ENVIRON ポリシー項目は、OPC 自動化オペレーターの実行環境を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"pacing_gate_info":"PACING GATE INFO ポリシー項目は、ペーシング・ゲートの情報を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"pacing_entry":"Pacing Gates エントリー・タイプは、ペーシング・ゲート(処理の流量制御)を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"passive_active":"パッシブ・モニターとアクティブ・モニター(Passive and Active Monitors)を扱う。コマンド処理シナリオの中で NetView 自動化テーブル(AT)エントリーを指定し、受動的監視と能動的監視を組み合わせる方法を説明する。",
"pdb_maint":"ポリシー・データベースの保守(Maintenance)を扱う。ポリシーの定義およびビルドは構成フォーカル・ポイント・システムで行われ、そこから各システムへ配布される。ポリシー・データベースの維持管理作業を説明する。",
"pdb_selection":"ポリシー・データベース選択(Policy Database Selection)を扱う。ポリシー・データベース選択パネルから対象データベースを選択し、編集・参照を開始する操作を説明する。",
"pdb_sel_list":"ポリシー・データベース選択リスト(Selection List)を扱う。関係選択リスト・パネル等とともに、利用可能なポリシー・データベースの一覧から対象を選択する操作を説明する。",
"policy_usage":"ポリシー定義の利用(Policy Definitions Usage)を扱う。ポリシーの定義およびビルドは SA z/OS 構成フォーカル・ポイント・システム上で行われ、そこから各システムへ構成が配布される。定義をどのように使用するかを説明する。",
"items_enterprise":"エンタープライズ用ポリシー項目(Policy Items for an Enterprise)を扱う。エンタープライズ・エントリーに割り当て可能なポリシー項目を一覧し、企業全体に関わる設定を定義する。",
"items_appdefaults":"アプリケーション・デフォルト用ポリシー項目を扱う。Application Defaults エントリーに割り当て可能なポリシー項目を一覧し、アプリケーションに共通適用する既定値を定義する。",
"items_appgroup":"アプリケーション・グループ用ポリシー項目を扱う。APPLGROUP INFO、APPLICATIONS、SERVICE PERIOD、RELATIONSHIPS、GENERATED RESOURCES、MEMBER OF などが含まれ、アプリケーション・グループ固有の設定を定義する。",
"items_applications":"アプリケーション用ポリシー項目を扱う。MESSAGES/USER DATA をはじめとする項目により、アプリケーションの状態をメッセージとして扱い、任意のコマンドの起動条件として割り当てできる。",
"items_autoops":"自動化オペレーター用ポリシー項目を扱う。Automation Operators エントリーに割り当て可能なポリシー項目を一覧し、自動化処理を実行するオペレーターを定義する。",
"items_cics":"CICS サブシステム用ポリシー項目を扱う。CICS 自動化に固有の設定項目を一覧し、CICS リージョンの起動・停止・監視を定義する。",
"items_db2":"Db2 サブシステム用ポリシー項目を扱う。Db2 自動化に固有の設定項目を一覧し、Db2 サブシステムの起動・停止・監視を定義する。",
"items_events":"イベント用ポリシー項目を扱う。Events エントリーに割り当て可能なポリシー項目を一覧し、リソースが活動・非活動であるべき条件を定義する。サービス期間用ポリシー項目と関連付けて表示される。",
"items_ims":"IMS サブシステム用ポリシー項目を扱う。IMS 自動化に固有の設定項目を一覧し、IMS サブシステムの起動・停止・監視を定義する。",
"items_jes2":"JES2 サブシステム用ポリシー項目を扱う。JES2 自動化に固有の設定項目を一覧し、JES2 の起動・停止・監視を定義する。",
"items_jes3":"JES3 サブシステム用ポリシー項目を扱う。JES3 自動化に固有の設定項目を一覧し、JES3 の起動・停止・監視を定義する。",
"items_processors":"メインフレーム・プロセッサー用ポリシー項目を扱う。Processor エントリーに割り当て可能なポリシー項目を一覧し、プロセッサー操作(ProcOps)対象を定義する。",
"items_monres":"モニター・リソース用ポリシー項目を扱う。Monitor Resource エントリーに割り当て可能なポリシー項目を一覧し、監視と健全性状態の伝播を定義する。",
"items_mvscomp":"MVS コンポーネント用ポリシー項目を扱う。MVS Component エントリーに割り当て可能なポリシー項目を一覧し、MVS 機能の自動化を定義する。",
"items_mvscompdef":"MVSCOMP デフォルト用ポリシー項目を扱う。MVSCOMP Defaults エントリーに割り当て可能なポリシー項目を一覧し、MVS コンポーネントに共通適用する既定値を定義する。",
"items_network":"ネットワーク用ポリシー項目を扱う。Network エントリーに割り当て可能なポリシー項目を一覧し、リソースが活動・非活動であるべき条件などを定義する。",
"items_notify":"通知オペレーター用ポリシー項目を扱う。Notify Operators エントリーに割り当て可能なポリシー項目を一覧し、通知先オペレーターを定義する。",
"items_opc":"OPC サブシステム用ポリシー項目を扱う。OPC 自動化に固有の設定項目を一覧し、OPC サブシステムの起動・停止・監視を定義する。",
"items_pacing":"ペーシング・ゲート用ポリシー項目を扱う。Pacing Gates エントリーに割り当て可能なポリシー項目を一覧し、処理の流量制御を定義する。",
"items_psm":"PSM プロセッサー用ポリシー項目を扱う。PSM(Processor Operations)プロセッサーに割り当て可能なポリシー項目を一覧し、プロセッサー操作を定義する。",
"items_remote":"リモート・ドメイン用ポリシー項目を扱う。Remote Domains エントリーに割り当て可能なポリシー項目を一覧し、リモート NetView ドメインとの連携を定義する。",
"items_clists":"常駐 CLIST 用ポリシー項目を扱う。Resident CLISTs エントリーに割り当て可能なポリシー項目を一覧し、常駐させる CLIST を定義する。",
"items_resref":"リソース参照用ポリシー項目を扱う。Resource References エントリーに割り当て可能なポリシー項目を一覧し、他リソースへの参照と関係を定義する。",
"items_serviceperiods":"サービス期間用ポリシー項目を扱う。サービス期間はリソースの可用性(リソースが活動・非活動であるべき時間帯=サービス・ウィンドウ)を定義する。既存のサービス期間エントリー選択時に表示されるポリシー項目群を説明する。",
"items_stdgroups":"標準グループ用ポリシー項目を扱う。Standard Group に割り当て可能なポリシー項目を一覧し、グループのメンバーや関係を定義する。",
"items_statusdisp":"状況表示(Status Display)用ポリシー項目を扱う。Status Display エントリーに割り当て可能なポリシー項目を一覧し、SDF などへの状況表示を定義する。",
"items_subgroups":"サブグループ用ポリシー項目を扱う。SubGroup に割り当て可能なポリシー項目を一覧し、サブグループのメンバーや関係を定義する。",
"items_sysplexdef":"スプレックス・デフォルト用ポリシー項目を扱う。Sysplex Defaults エントリーに割り当て可能なポリシー項目を一覧し、スプレックス全体に共通適用する既定値を定義する。",
"items_sysplexgroups":"スプレックス・グループ用ポリシー項目を扱う。Sysplex Group に割り当て可能なポリシー項目を一覧し、スプレックス・グループのメンバーや関係を定義する。",
"items_sysdef":"システム・デフォルト用ポリシー項目を扱う。System Defaults エントリーに割り当て可能なポリシー項目を一覧し、システムに共通適用する既定値を定義する。",
"items_systems":"システム用ポリシー項目を扱う。System エントリーに割り当て可能なポリシー項目を一覧し、システム単位の自動化設定を定義する。",
"items_triggers":"トリガー用ポリシー項目を扱う。Triggers エントリーに割り当て可能なポリシー項目を一覧し、サービス期間やイベントと連動する起動・停止条件を定義する。",
"items_etpairs":"ユーザー E-T ペア用ポリシー項目を扱う。User E-T Pairs エントリーに割り当て可能なポリシー項目を一覧し、エントリー/タイプ・ペアのユーザー・データを定義する。",
"items_uss":"USS サブシステム用ポリシー項目を扱う。USS(UNIX System Services)自動化に固有の設定項目を一覧し、USS サブシステムの起動・停止・監視を定義する。",
"objects_items":"ポリシー・オブジェクトとポリシー項目(Policy Objects and Policy Items)の概念を扱う。エントリー(ポリシー・オブジェクト)とそれに割り当てる各種ポリシー項目の関係を整理し、ポリシー定義の基本構造を説明する。",
"predef_msgs":"PREDEFINED MESSAGES ポリシー項目は、事前定義メッセージを扱う項目。IEF238D メッセージのコード突合時に渡される条件に応じて、事前定義された自動化応答を制御する。",
"predef_sa_msgs":"事前定義の SA z/OS メッセージ(Predefined SA z/OS Messages)を扱う。アプリケーションの一部の状態をメッセージとして扱い、任意のコマンドの起動条件として割り当てできる。MESSAGES/USER DATA ポリシー項目と連携する。",
"processor_entry":"Processor エントリー・タイプは、メインフレーム・プロセッサーを定義するエントリー。プロセッサー操作(ProcOps)対象を定義し、サービス期間用ポリシー項目と関連付けて表示される。",
"processor_item":"PROCESSOR ポリシー項目は、プロセッサーに関する定義を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"procops_fp":"PROCOPS FOCAL POINTS ポリシー項目は、プロセッサー操作のフォーカル・ポイントを定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"recovery_opts":"RECOVERY OPTIONS ポリシー項目は、リソースの復旧オプションを定義する項目。障害時の自動復旧動作(再起動回数や条件など)を設定する。",
"references_item":"REFERENCES ポリシー項目は、リソース参照(他リソースへの参照)を定義する項目。リソース参照エントリーと連携し、参照関係を管理する。",
"relationships":"RELATIONSHIPS ポリシー項目は、アプリケーション・アプリケーション・グループ・モニター・リソース・リソース参照の各エントリーで共通の機能を持つ項目。複数の関係を指定し、それらリソースの起動・停止の自動化に用いる。関係選択リスト・パネルで既存の関係を確認できる。",
"remote_entry":"Remote Domains エントリー・タイプは、リモート NetView ドメインを定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"clists_entry":"Resident CLISTs エントリー・タイプは、常駐させる CLIST を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"resource_def":"RESOURCE DEFINITIONS ポリシー項目は、リソース定義に関する設定を行う項目。関係選択リスト・パネルやアプリケーション・グループ用 SERVICE PERIOD 項目と関連付けて、リソースの定義を管理する。",
"resource_info":"RESOURCE INFO ポリシー項目は、リソースの情報を表示・設定する項目。関係選択リスト・パネルやアプリケーション・グループ用 SERVICE PERIOD 項目と関連付けて、リソースの基本情報を管理する。",
"resref_entry":"Resource References エントリー・タイプは、他リソースへの参照を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"resources_item":"RESOURCES ポリシー項目は、対象に含めるリソースを定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"restrictions":"制限事項(Restrictions)を扱う。代替・第三構成のビルドなどに関する機能上の制限を整理し、利用時に留意すべき点を説明する。",
"scenario_env":"シナリオ環境と挙動(Scenario Environment and Behavior)を扱う。サービス期間とオペレーター要求の組み合わせ時の動作(スケジュールによる要求が優先される等)を含め、シナリオ実行時の前提環境と挙動を説明する。",
"scenarios":"カスタマイズ・ダイアログの使用シナリオ(第 3 章)を扱う。リソースの操作、スケジュール(サービス期間)の使用、トリガーとイベントの使用など、適切な自動化ポリシーを実装するための一連のシナリオを提供する。",
"schedule_override":"スケジュール・オーバーライド(Schedule Override)を扱う。コマンド処理シナリオの中で NetView 自動化テーブル(AT)エントリーを指定し、サービス期間によるスケジュールを一時的に上書きする方法を説明する。",
"sdf_details":"SDF DETAILS ポリシー項目は、状況表示機能(SDF)の詳細を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"sdf_focalpoint":"SDF FOCALPOINT ポリシー項目は、SDF(状況表示機能)のフォーカル・ポイントを定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"select":"選択(Select)操作を扱う。ポリシー項目の選択方法を説明し、目的の項目を選んで編集・参照に進む操作を示す。",
"selective_conv":"選択的ポリシー・データベース変換(Selective Policy Database Conversion)を扱う。ポリシーの定義・ビルドは構成フォーカル・ポイント・システムで行われ、そこから各システムへ配布される。一部のエントリーのみを選択して変換する方法を説明する。",
"send_cmd_opers":"SEND COMMAND OPERS ポリシー項目は、コマンド送信オペレーターを定義する項目。アプリケーションの一部の状態をメッセージとして扱い、任意のコマンドの起動条件として割り当てできる。MESSAGES/USER DATA ポリシー項目と連携する。",
"service_period_item":"SERVICE PERIOD ポリシー項目は、リソースにサービス期間をリンクする項目。アプリケーション・グループ用パネルでサービス期間を割り当てると、配下リソースが指定の時間帯に自動起動・自動停止される。関係選択リスト・パネルと併せて利用される。",
"serviceperiods_entry":"Service Periods エントリー・タイプは、サービス期間を定義するエントリー。サービス期間はリソースが活動・非活動であるべき時間帯(サービス・ウィンドウ)の集合であり、可用性を定義する。",
"service_window":"SERVICE WINDOW ポリシー項目は、サービス・ウィンドウ(リソースが活動・非活動であるべき時間帯)を定義する項目。FROM/TO 時刻の指定によりサービス期間内の時間間隔を構成する。既にアクティブなサービス期間の変更は、過去のオーバーライドとの不整合を生じうる点に注意する。",
"at_scope":"AT/MRT スコープの設定(Setting AT/MRT Scope)を扱う。自動化テーブル(AT)およびメッセージ・リビジョン・テーブル(MRT)の適用範囲を設定する。各システムには自動化マネージャーと自動化エージェントが存在する。",
"shutdown_item":"SHUTDOWN ポリシー項目は、リソースの停止時に発行するコマンドまたはコマンド・リストを定義する項目。発行するコマンドを入力し、システム・コマンドの場合は MVS を前置する必要がある。STARTUP ポリシー項目と対になる。",
"soap_server":"SOAP SERVER ポリシー項目は、SOAP サーバーに関する定義を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"special_chars":"特殊文字(Special Characters)を扱う。AT エントリーや定義で使用できる特殊文字の意味と扱いを説明する。NetView 自動化テーブルの管理方法は関連マニュアルに詳述される。",
"special_resource":"SPECIAL RESOURCE ポリシー項目は、特殊リソースを定義する項目。関係選択リスト・パネルやアプリケーション・グループ用 SERVICE PERIOD 項目と関連付けて、特殊リソースの定義を管理する。",
"spec_options":"ポリシー・データベースのオプション指定(Specifying Options for Policy Databases)を扱う。ポリシー・データベースに対する各種オプションを設定し、ビルドや変換の挙動を制御する。",
"start_datamgmt":"データ管理の開始パネル(Start Panel for Data Management)を扱う。データ管理機能の起点となるパネルから、インポート・エクスポート・テキスト・ファイル更新などの操作へ進む。",
"startup_item":"STARTUP ポリシー項目は、リソースの起動時に発行するコマンドまたはコマンド・リストを定義する項目。発行するコマンドを入力し、システム・コマンドの場合は MVS を前置する必要がある。SHUTDOWN ポリシー項目と対になる。",
"statusdisp_entry":"Status Display エントリー・タイプは、状況表示(SDF など)を定義するエントリー。監視対象の健全性状態が APL や APG へ伝播し、総合的な状態判定に反映される。",
"step1_userdata":"ステップ 1:ユーザー定義データの指定を扱う。ユーザー定義データを用いたメッセージ処理の最初の手順として、MESSAGES/USER DATA ポリシー項目でユーザー・データを指定する。",
"step1_userdialog":"ステップ 1:カスタマイズ・ダイアログでのユーザー・データ指定を扱う。ユーザー E-T ペアの活用シナリオの第一歩として、ダイアログ上でユーザー・データを定義する手順を説明する。",
"step2_access":"ステップ 2:ユーザー・データへのアクセスを扱う。定義済みのユーザー・データを自動化処理から参照・取得する手順を説明する。",
"step2_commands":"ステップ 2:コマンドの指定を扱う。メッセージ処理シナリオの中で、検出メッセージに応答して発行するコマンドを指定する手順を説明する。",
"step3_at":"ステップ 3:NetView 自動化テーブル(AT)の更新を扱う。メッセージ処理シナリオで、対象メッセージを契機とする AT エントリーを指定して自動化を有効にする手順を説明する。",
"step4_rexx":"ステップ 4:REXX スクリプトの作成を扱う。メッセージ処理シナリオの最終段階として、ユーザー・データを処理する REXX スクリプトを作成する手順を説明する。",
"subgroup_entry":"SubGroup エントリー・タイプは、グループ階層の下位に位置するサブグループを定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"supported_policies":"サポートされるポリシー(Supported Policies)を扱う。リソース(VTAM/APL 等)に対する関係定義の例(説明・シーケンス番号・自動化 PASSIVE・チェーニング WEAK・条件 WhenDown など)を通じて、定義可能なポリシーの種類を示す。",
"symbol_desc":"SYMBOL DESCRIPTION ポリシー項目は、システム自動化シンボルの説明を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"sysplexdef_entry":"Sysplex Defaults エントリー・タイプは、スプレックスに共通適用する既定値を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"sysplex_item":"SYSPLEX ポリシー項目は、スプレックスに関する定義を行う項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"sys_app_overrides":"システムおよびアプリケーション固有のオーバーライド(System and Application Specific Overrides)を扱う。共通定義に対し、システムやアプリケーション単位で個別の上書き設定を行う方法を説明する。",
"system_assoc":"SYSTEM ASSOCIATION ポリシー項目は、アプリケーションをどのシステムに関連付けるかを定義する項目。生成リソース・パネルに表示されるリソース生成の基礎となり、アプリケーションとシステムの対応付けを管理する。",
"sysdef_entry":"System Defaults エントリー・タイプは、システムに共通適用する既定値を定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"system_entry":"System エントリー・タイプは、自動化対象システムを定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"system_info":"SYSTEM INFO ポリシー項目は、システムの基本情報を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"tape_entry":"Tape Attendance エントリー・タイプは、テープ・アテンダンス(テープ操作の自動応答)を定義するエントリー。IEF238D メッセージのコード突合時に渡される条件に応じて、テープ操作への自動応答を制御する。",
"target_sysinfo":"TARGET SYSTEM INFO ポリシー項目は、ターゲット・システムの情報を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。",
"terms_conditions":"製品ドキュメントの使用条件(Terms and conditions)を扱う。IBM 製品ドキュメントの利用に関する条件を記載する法的・運用上の注記である。",
"sa_predef_entry":"+SA_PREDEFINED_MSGS MVS コンポーネント・エントリーを扱う。SA z/OS が事前定義するメッセージ群を保持する特別な MVS コンポーネント・エントリーであり、事前定義メッセージの変更時に参照される。",
"ingmsgsa":"INGMSGSA 自動化テーブルを扱う。各システムにはプライマリおよび任意のセカンダリ自動化マネージャーと自動化エージェントが存在する。INGMSGSA は SA z/OS が提供する NetView 自動化テーブルであり、製品標準のメッセージ自動化を担う。",
"netview_at":"NetView 自動化テーブル(AT)を扱う。各システムにはプライマリおよび任意のセカンダリ自動化マネージャーと自動化エージェントが存在する。AT はメッセージ駆動の自動化を定義するテーブルであり、CMD/REP 等のアクションを記述する。",
"mrt":"NetView メッセージ・リビジョン・テーブル(MRT)を扱う。メッセージの内容や属性をテーブル定義に基づいて改訂(リビジョン)する仕組みであり、AT による自動化処理の前段でメッセージを整形する。",
"thresholds":"THRESHOLDS ポリシー項目は、エラー閾値(一定時間内の発生回数など)を定義する項目。設定値はビルドにより構成ファイルへ反映され、生成リソース・パネルおよびアプリケーション用 SYSTEM ASSOCIATION 項目と関連付けて管理される。閾値超過時の復旧動作の判断に用いる。",
"timers_entry":"Timers エントリー・タイプは、タイマー(定時実行)を定義するエントリー。IEF238D メッセージのコード突合時に渡される条件に応じた処理と関連付けて、時間契機の自動化を構成する。",
"timers_item":"TIMERS ポリシー項目は、タイマーに関する定義を行う項目。IEF238D メッセージのコード突合時に渡される条件に応じて、時間契機の自動化アクションを制御する。",
"trigger_item":"TRIGGER ポリシー項目は、リソースにトリガーを割り当てる項目。アプリケーション・グループ用トリガー・パネル(TRIGGER1 XRFTRIG 等)で、サービス期間と連動する起動・停止契機を定義する。",
"triggers_entry":"Triggers エントリー・タイプは、トリガー(起動・停止の契機)を定義するエントリー。リソースが活動・非活動であるべき条件を扱い、サービス期間用ポリシー項目と関連付けて表示される。",
"textfile_update2":"テキスト・ファイルを用いたポリシー・オブジェクトの更新(Updating)を扱う。データ管理機能でテキスト・ファイルを取り込み、既存オブジェクトの定義を更新する手順を説明する。",
"upward_class":"UPWARD CLASS ポリシー項目は、当該アプリケーションから上位クラスへの単一の継承リンクを定義する項目。上位クラスで定義したポリシーを継承し、MESSAGES/USER DATA 等と連携してメッセージ駆動の自動化を構成する。",
"etpairs_entry":"User E-T Pairs エントリー・タイプは、ユーザー定義のエントリー/タイプ・ペアを定義するエントリー。ビルド延期の挙動が適用され、APL/MVC タイプとの間で AT 影響データの変更が検査される。",
"user_msg_classes":"USER MSG CLASSES ポリシー項目は、ユーザー・メッセージ・クラスを定義する項目。STARTUP・SHUTDOWN・THRESHOLDS・MINOR RESOURCES などの関連ポリシー項目と併せて、メッセージの分類を管理する。",
"user_functions":"ユーザー作成関数(User-written Functions)を扱う。CMD・REP・AT などのアクションのために、利用者が独自に作成した関数を AT エントリーで利用する仕組み。NetView 自動化テーブルの管理方法は関連マニュアルに詳述される。",
"assistive":"支援技術(Assistive Technologies)の利用を扱う。アクセシビリティの観点から、支援技術を用いて製品インターフェースを操作する方法を説明する。",
"sample_policies":"SA z/OS サンプル・ポリシーの利用(Using SA z/OS Sample Policies)を扱う。*BASE などの提供サンプル・ポリシーを基にポリシー・データベースを構築する方法を説明する。",
"system_symbols":"システム・シンボルとシステム自動化シンボルの使用を扱う。MVS のシステム・シンボルおよび SA z/OS 固有の自動化シンボルを用いて、定義をシステム間で共通化・クローン展開する方法を説明する。",
"using_dialog":"カスタマイズ・ダイアログの使用(第 2 章)を扱う。ダイアログの起動、ナビゲーション、ポリシー・オブジェクトの作成・参照・削除など、基本操作を体系的に説明する。",
"where_used":"WHERE USED ポリシー項目は、当該エントリーがどこで使用されているかを表示する汎用項目。多くのエントリー・タイプで共通利用でき、ポリシー項目内のデータ検索方法と関連する。",
"who_should":"本書を使用すべき読者(Who Should Use This Publication)を扱う。本マニュアルの対象読者と前提知識を示す導入的な記述である。",
"work_monres":"MONITOR リソースの操作(Working with MONITOR Resources)を扱う。モニター・リソースの作成・監視・健全性状態の伝播など、監視リソースを運用する手順を説明する。",
"write_batch":"バッチ・ジョブによるファイルへのデータ書き出し(Write Data to File)を扱う。データ管理機能でポリシー・データベースの内容をバッチ・ジョブによりファイルへ出力する手順を説明する。",
"library":"Z System Automation ライブラリーを扱う。SA z/OS で CICS・Db2・IMS などの製品自動化コンポーネントを単純かつ一貫した方法で監視・運用するための関連マニュアル群(ライブラリー)を案内する。",
    }
    return D.get(cat, "")

def src(page):
    return f"{MAN} p.{page}"

def make_quiz(title, cat, naiyou):
    # build a JP quiz with 4 choices; correct describes the item; distractors are other categories
    distractors_pool = {
"policy_item":"NetView 自動化テーブルの構文チェックを有効化する設定である",
"build":"ポリシー・データベースを新規に作成する手順である",
"entry":"製品ドキュメントの使用条件を記載した法的注記である",
"scenario":"プロセッサー操作のフォーカル・ポイントを定義する項目である",
"msg":"サービス・ウィンドウの FROM/TO 時刻を定義する項目である",
"other":"支援技術を用いた操作方法を説明する項目である",
    }
    # Build correct answer: first sentence of naiyou (trimmed)
    correct = naiyou.split("。")[0] + "。"
    if len(correct) > 70:
        correct = correct[:68] + "…"
    ds = list(distractors_pool.values())
    choices = [correct, ds[0], ds[2], ds[4]]
    q = f"{MAN} における『{title}』の説明として最も適切なものはどれか。"
    explanation = f"『{title}』は{naiyou.split('。')[0]}。他の選択肢は無関係な別項目の説明であり該当しない。"
    return {"q": q, "choices": choices, "answer": 0, "explanation": explanation}

def make_verify(title, cat, page):
    steps = []
    steps.append("[セッション環境] SA z/OS カスタマイズ・ダイアログ (INGDLG) / ISPF")
    steps.append(f"[手順1] TSO READY から INGDLG を起動し、ポリシー・データベース選択パネルで対象 PDB を選択する。")
    steps.append(f"[手順2] エントリー・タイプ選択パネルで対象エントリーを選び、『{title}』に該当するポリシー項目またはパネルを開く。")
    steps.append(f"[手順3] {MAN} p.{page} の記述と当該パネルの表示内容(項目名・既定値・関連項目)を突き合わせて確認する。")
    steps.append("[手順4] 必要に応じて値を更新し、構成ビルド(オプション1 / Type=MODIFIED)を実行して構成ファイルへ反映する。")
    steps.append("[手順5] ビルド・ログおよび NetView NETLOG / SYSLOG にエラー(AOFxxx / INGxxx)が無いことを確認し、結果を記録する。")
    return "\n".join(steps)

out_rows = []
missing = []
for rid, title, page, cat in ROWS:
    naiyou = jp_intro(title, cat)
    if not naiyou:
        missing.append((rid, title, cat))
        naiyou = f"{title} は、{MAN}(p.{page})で説明される自動化ポリシー定義の項目である。カスタマイズ・ダイアログ上で該当エントリーまたはポリシー項目として定義し、ビルドによって構成ファイルへ反映する。"
    quiz = make_quiz(title, cat, naiyou)
    verify = make_verify(title, cat, page)
    out_rows.append({
        "row_id": rid,
        "title": title,
        "naiyou_jp": naiyou,
        "verify_steps": verify,
        "quiz": quiz,
        "source": src(page),
        "rag_hit": f"TSA_z_OS_4.3_Defining_Automation_Policy p.{page}",
    })

doc = {
    "page": "g056",
    "product": "IBM TSA z/OS 4.3",
    "total_rows": 274,
    "target_rows": len(ROWS),
    "fixed_count": len(out_rows),
    "rows": out_rows,
}

with open(r"C:\kvba\zos-atoms-site\_phase2_outputs\g056_fixed.json", "w", encoding="utf-8") as f:
    json.dump(doc, f, ensure_ascii=False, indent=1)

print("rows:", len(out_rows))
print("missing categories (used fallback):", missing)
# forbidden token check
import io
txt = json.dumps(doc, ensure_ascii=False)
for tok in ["原文ママ","MCP","RAG","ChromaDB","chunk","search_manual","ADR-","corpus","verbatim","職場"]:
    if tok in txt:
        print("FORBIDDEN PRESENT:", tok, txt.count(tok))
print("English-fragment check (long ASCII runs):")
import re as _re
bad = _re.findall(r'[A-Za-z]{4,}(?:\s+[A-Za-z]{4,}){4,}', txt)
print("long english runs:", len(bad), bad[:5])
